services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_web
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html/src          
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
      SERVER_BASE_URL: "http://web:80"
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_worker
    volumes:
      - ./src:/var/www/html/src          
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
    working_dir: /var/www/html
    command: php bin/start_game_worker.php   
    depends_on:
      - rabbitmq
      - redis
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data: